import Head from 'next/head'
import LandingPage from '../components/LandingPage'

export default function Landing() {
    return (
        <>
            <Head>
                <title>RainCheck</title>
                <meta name="RainCheck" content="Generated by create next app" />
            </Head>
            <LandingPage />
        </>
    )
}
